### ISSUE TITLE
VPAID dimensions exceed container in some browsers

### ISSUE THREAD

**Issue by edrpls** [gumgum/gg-ez-vp#49]
VPAID on Safari may choose a file size larger than the container. We need to ensure the video fits the container so that it doesn't push the controls or the player itself.

**Comment by w-dayrit** [comment]
VPAID tag (ex: ad 17067 in ads account) isn't rendering properly on desktop chrome.

**Comment by w-dayrit** [comment]
Same issue above with VAST tag (ex: ad # 17351)

**Comment by edrpls** [comment]
@w-dayrit I haven't been able to reproduce this issue on the ids you mentioned. I think this was fixed by [resizing the creative](https://github.com/gumgum/gg-ez-vp/commit/3c506e575d0af99473464be2b522fe97fb31dbb3#diff-5a661f1c4a05e5b4a5e419107d6fa714R40). Could you please test it and see if that's the case for you as well?
