### ISSUE TITLE
video doesn't play on certain devices

### ISSUE THREAD

**Issue by taekimm** [gumgum/gg-ez-vp#89]
It seems that for certain devices running iOS 13.5.1 - the video does not load/autoplay correctly.

The bug has been replicated on 2 specific iOS devices (an iPhone X & an iPhone XS) so far - but cannot seem to replicate on demand.
I've had a friend w/ an iOS 13.5.1 go to the page w/ the video and it loads and plays fine for them, but not for another person.

Can confirm that all the people testing do not have a VPN/ad blocking on their iOS devices.
Issue has been detected on Safari & Chrome.

**Comment by edrpls** [comment]
This was not reproducible, and we haven't received any updates or complaints about this. Closing.
